
const state={data:null,selectedDay:"weekday",currentTrips:[]};
const $=id=>document.getElementById(id);
function sec(t){const[a,b,c="0"]=String(t).split(":").map(Number);return a*3600+b*60+Number(c)}
function hhmm(s){const h=Math.floor(s/3600)%24,m=Math.floor((s%3600)/60);return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}
function nowSeconds(){const d=new Date();return d.getHours()*3600+d.getMinutes()*60+d.getSeconds()}
function todayType(){const d=new Date().getDay();return d===0?"holiday":d===6?"saturday":"weekday"}
function tripsForDay(type){if(!state.data)return[];const key=type==="auto"?todayType():type;return state.data.timetable[key]||[]}
async function loadData(){const res=await fetch("./route-data.json?v=3",{cache:"no-store"});if(!res.ok)throw new Error("route-data.json がまだありません。GitHubのActionsが完了するまで数分待ってください。");state.data=await res.json();$("lastUpdated").textContent=`時刻表データ更新：${state.data.generatedAt||"取得済み"}`}
function renderNext(){const selected=sec($("timeInput").value+":00");const trips=tripsForDay($("dayType").value).filter(t=>t.departSec>=selected).slice(0,3);state.currentTrips=trips;if(!trips.length){$("nextBuses").innerHTML='<div class="loading">指定時刻以降の便がありません。</div>';return}$("nextBuses").innerHTML=trips.map((t,i)=>`<button class="bus-card" data-trip-index="${i}"><div class="bus-top"><div><div class="departure">${t.depart}発</div><div class="destination">南常盤台 → 王子五丁目</div></div><div class="delay">遅れ未接続</div></div><div class="bus-sub">王78・王子駅前方面　${state.data.stops.length-1}区間 <span class="chevron">›</span></div></button>`).join("");document.querySelectorAll(".bus-card").forEach(btn=>btn.addEventListener("click",()=>openTrip(Number(btn.dataset.tripIndex))))}
function renderTimetable(type=state.selectedDay){state.selectedDay=type;document.querySelectorAll(".day-switch button").forEach(b=>b.classList.toggle("active",b.dataset.day===type));const trips=tripsForDay(type),grouped=new Map();trips.forEach(t=>{const h=Math.floor(t.departSec/3600),m=Math.floor((t.departSec%3600)/60);if(!grouped.has(h))grouped.set(h,[]);grouped.get(h).push({m,sec:t.departSec})});const next=trips.find(t=>t.departSec>=nowSeconds())?.departSec;$("timetable").innerHTML=[...grouped.entries()].map(([h,mins])=>`<div class="timetable-hour"><div class="hour">${String(h).padStart(2,"0")}</div><div class="minutes">${mins.map(x=>{const cls=x.sec<nowSeconds()?"past":x.sec===next?"next":"";return `<span class="minute ${cls}">${String(x.m).padStart(2,"0")}</span>`}).join("")}</div></div>`).join("")}
function openTrip(i){const trip=state.currentTrips[i];if(!trip)return;$("nextPanel").classList.add("hidden");$("timetablePanel").classList.add("hidden");$("detailPanel").classList.remove("hidden");document.querySelector(".tabs").classList.add("hidden");$("detailHeader").innerHTML=`<div class="detail-card"><div class="detail-title">${trip.depart}発</div><div class="detail-meta">南常盤台 → 王子五丁目／王78・王子駅前方面</div></div>`;$("stopList").innerHTML=state.data.stops.map((s,i)=>`<li class="stop-item">${s.name}<span class="stop-time">${trip.stopTimes?.[i]||""}</span></li>`).join("")}
function showTab(name){$("detailPanel").classList.add("hidden");document.querySelector(".tabs").classList.remove("hidden");$("nextPanel").classList.toggle("hidden",name!=="next");$("timetablePanel").classList.toggle("hidden",name!=="timetable");document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===name));if(name==="timetable")renderTimetable()}
async function refresh(){try{$("nextBuses").innerHTML='<div class="loading">データを読み込んでいます…</div>';await loadData();renderNext();renderTimetable()}catch(e){$("lastUpdated").textContent="読み込み失敗";$("nextBuses").innerHTML=`<div class="error">${e.message}</div>`}}
function init(){const d=new Date();$("timeInput").value=`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;$("dayType").value="auto";document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>showTab(b.dataset.tab)));document.querySelectorAll(".day-switch button").forEach(b=>b.addEventListener("click",()=>renderTimetable(b.dataset.day)));$("backBtn").addEventListener("click",()=>showTab("next"));$("refreshBtn").addEventListener("click",refresh);$("timeInput").addEventListener("change",renderNext);$("dayType").addEventListener("change",renderNext);refresh()}
document.addEventListener("DOMContentLoaded",init);
